version: "2"
services:
  php:
    build: ./docker/php
    volumes:
      - ./app:/app 
  web: 
    image: "nginx:1.17.0-alpine" 
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"  
    links:
      - "php" 